apiVersion: apps/v1
kind: ServiceAccount
kind: Deployment
metadata:
  namespace: "mc-analytics"
  name: bqapp
  labels: 
    image_version: "0.4"
    deploy_version: "0.2"
spec:
  serviceAccountName: bqappsa
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
  replicas: 1
  selector:
    matchLabels:
      app: bqapp
  template:
    metadata:
      labels:
        app: bqapp
    spec:
      containers:
      - name: bqapp
        image: "us-east1-docker.pkg.dev/gcp-mc-demo-prime/myapp/mc-analytics:0.4"
        ports:
        - containerPort: 8080
        env:
        - name: CONTAINER_PORT
          value: "8080"
        - name: ENV
          value: "env1-gcp"
        - name: BQ_DATASET_ID
          valueFrom:
            secretKeyRef:
              name: bqapp-credentials
              key: bq_dataset_id
        - name: BQ_TABLE_ID
          valueFrom:
            secretKeyRef:
              name: bqapp-credentials
              key: bq_table_id
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "bqapp-hpa"
  labels:
    app: "bqapp"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "bqapp"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bqapp
spec:
  type: LoadBalancer
  selector:
    app: bqapp
  ports:
  - name: http
    port: 80
    targetPort: 8080
